name: Deploy to Production environment

on:
  push:
    branches: [main]

jobs:
  deploy:
    environment:
      name: production

    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Use Firebase environment
        uses: w9jds/firebase-action@v12.8.0
        with:
          args: use production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_DEV }}

      - name: Build
        run: npm run build
        env:
          VITE_MIXPANEL_API_KEY: ${{ secrets.VITE_MIXPANEL_API_KEY }}

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v12.8.0
        with:
          args: deploy --only hosting:latam-landing-25afc
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_DEV }}
